// code/renderers/react/template/components/Form.jsx
import React, { useState } from 'react';

/**
 * Form
 * @param {object} props
 * @param {function} props.onSuccess
 */
export const Form = ({ onSuccess }) => {
  const [value, setValue] = useState('');
  const [complete, setComplete] = useState(false);

  function onSubmit(event) {
    event.preventDefault();
    onSuccess(value);

    setTimeout(() => setComplete(true), 500);
    setTimeout(() => setComplete(false), 1500);
  }

  return (
    <form id="interaction-test-form" onSubmit={onSubmit}>
      <label>
        Enter Value
        <input
          type="text"
          data-testid="value"
          value={value}
          required
          onChange={(event) => setValue(event.target.value)}
        />
      </label>
      <button type="submit">Submit</button>
      {complete && <p>Completed!!</p>}
    </form>
  );
};

// code/renderers/vue3/template/components/Form.vue
<template>
  <form id="interaction-test-form" @submit.prevent="onSubmit">
    <label>
      Enter Value
      <input type="text" data-testid="value" :value="value" required @click="setValue" />
    </label>
    <button type="submit">Submit</button>
    <p v-if="complete">Completed!!</p>
  </form>
</template>

<script>
export default {
  name: 'my-form',

  props: {
    onSuccess: {
      type: Function,
    },
  },

  data() {
    return {
      value: '',
      complete: false,
    };
  },

  methods: {
    setValue(event) {
      this.value = event.target.value;
    },
    onSubmit() {
      this.onSuccess(this.value);
      setTimeout(() => (this.complete = true), 500);
    },
  },
};
</script>
