// renderers/preact/src/preview/render.tsx
import * as preact from 'preact';
import dedent from 'ts-dedent';
import { RenderContext } from '@storybook/store';
import { StoryFnPreactReturnType } from './types';
import { PreactFramework } from './types-6-0';

let renderedStory: Element;

function preactRender(story: StoryFnPreactReturnType | null, domElement: Element): void {
  // @ts-ignore
  if (preact.Fragment) {
    // Preact 10 only:
    preact.render(story, domElement);
  } else {
    renderedStory = preact.render(story, domElement, renderedStory) as unknown as Element;
  }
}

const StoryHarness: preact.FunctionalComponent<{
  name: string;
  title: string;
  showError: RenderContext<PreactFramework>['showError'];
  storyFn: () => any;
  domElement: Element;
}> = ({ showError, name, title, storyFn, domElement }) => {
  const content = preact.h(storyFn as any, null);
  if (!content) {
    showError({
      title: `Expecting a Preact element from the story: "${name}" of "${title}".`,
      description: dedent`
        Did you forget to return the Preact element from the story?
        Use "() => (<MyComp/>)" or "() => { return <MyComp/>; }" when defining the story.
      `,
    });
    return null;
  }
  return content;
};

export function renderToDOM(
  { storyFn, title, name, showMain, showError, forceRemount }: RenderContext<PreactFramework>,
  domElement: Element
) {
  if (forceRemount) {
    preactRender(null, domElement);
  }

  showMain();

  preactRender(preact.h(StoryHarness, { name, title, showError, storyFn, domElement }), domElement);
}

// app/stencil/src/client/preview/render.ts
import { document } from 'global';
import dedent from 'ts-dedent';

import { renderVdom, registerHost, getHostRef } from '@stencil/core/internal/client';
import { RenderContext } from './types';

const rootElement = document.getElementById('root');
registerHost(rootElement, { $flags$: 0, $tagName$: 'story-root' });
const hostRef = getHostRef(rootElement);

export default function renderMain({
  storyFn,
  showMain,
  forceRender,
  showError,
  kind,
  name,
}: RenderContext) {
  const element = storyFn();

  showMain();

  if (typeof (element as any).$tag$ === 'string') {
    if (!forceRender) {
      renderVdom(hostRef, undefined);
    }

    renderVdom(hostRef, element);
  } else {
    showError({
      title: `Expecting a JSX snippet from the story: "${name}" of "${kind}".`,
      description: dedent`
        Did you forget to return the jsx snippet from the story?
        Use "() => <your-custom-element />" or when defining the story.
      `,
    });
  }
}
