// code/renderers/react/template/components/Form.jsx
import React, { useState } from 'react';

/**
 * Form
 * @param {object} props
 * @param {function} props.onSuccess
 */
export const Form = ({ onSuccess }) => {
  const [value, setValue] = useState('');
  const [complete, setComplete] = useState(false);

  function onSubmit(event) {
    event.preventDefault();
    onSuccess(value);

    setTimeout(() => setComplete(true), 500);
    setTimeout(() => setComplete(false), 1500);
  }

  return (
    <form id="interaction-test-form" onSubmit={onSubmit}>
      <label>
        Enter Value
        <input
          type="text"
          data-testid="value"
          value={value}
          required
          onChange={(event) => setValue(event.target.value)}
        />
      </label>
      <button type="submit">Submit</button>
      {complete && <p>Completed!!</p>}
    </form>
  );
};

// code/renderers/svelte/template/components/Form.svelte
<script>
  /**
   * Callback for when the form succeeds
   */
  export let onSuccess;

  let value = '';
  function handleClick(event) {
    value = event.target.value;
  }

  let complete = false;
  function handleSubmit() {
    onSuccess(value);

    setTimeout(() => {
      complete = true;
    }, 500);
  }
</script>

<form id="interaction-test-form" on:submit|preventDefault={handleSubmit}>
  <label>
    Enter Value
    <input type="text" data-testid="value" {value} required on:click={handleClick} />
  </label>
  <button type="submit">Submit</button>
  {#if complete}<p>Completed!!</p>{/if}
</form>
