// code/renderers/preact/template/components/Pre.jsx
/**
 * Pre component
 * @param {object} props
 * @param {object} [props.style]
 * @param {object} [props.object]
 * @param {string} [props.text]
 */
export const Pre = ({ style = {}, object = null, text = '' }) => (
  <pre style={style} data-testid="pre">
    {object ? JSON.stringify(object, null, 2) : text}
  </pre>
);

// code/renderers/svelte/template/components/Pre.svelte
<script>
  /**
   * Styles to use for this component
   */
  export let style = {};
  /**
   * Object to log
   */
  export let object;
  /**
   * Text content to log
   */
  export let text = '';

  $: finalText = object ? JSON.stringify(object, null, 2) : text;
</script>

<pre data-testid="pre" {style}>{finalText}</pre>
