// code/renderers/react/src/types.ts
import type { ComponentType } from 'react';
import type { WebRenderer } from '@storybook/types';

export type { RenderContext, StoryContext } from '@storybook/types';

/**
 * @deprecated Use `ReactRenderer` instead.
 */
export type ReactFramework = ReactRenderer;
export interface ReactRenderer extends WebRenderer {
  component: ComponentType<this['T']>;
  storyResult: StoryFnReactReturnType;
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}

export type StoryFnReactReturnType = JSX.Element;

// code/renderers/web-components/src/types.ts
import type { StoryContext as StoryContextBase, WebRenderer } from '@storybook/types';
import type { TemplateResult, SVGTemplateResult } from 'lit';

export type StoryFnHtmlReturnType = string | Node | TemplateResult | SVGTemplateResult;

export type StoryContext = StoryContextBase<WebComponentsRenderer>;

/**
 * @deprecated Use `WebComponentsRenderer` instead.
 */
export type WebComponentsFramework = WebComponentsRenderer;
export interface WebComponentsRenderer extends WebRenderer {
  component: string;
  storyResult: StoryFnHtmlReturnType;
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}
