// code/renderers/svelte/template/cli/Button.svelte
<script>
  import './button.css';
  import { createEventDispatcher } from 'svelte';
  /**
   * Is this the principal call to action on the page?
   */
  export let primary = false;

  /**
   * What background color to use
   */
  export let backgroundColor = undefined;
  /**
   * How large should the button be?
   */
  export let size = 'medium';
  /**
   * Button contents
   */
  export let label = '';

  let mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';

  let style = backgroundColor ? `background-color: ${backgroundColor}` : '';

  const dispatch = createEventDispatcher();

  /**
   * Optional click handler
   */
  export let onClick = (event) => {
    dispatch('click', event);
  };
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  on:click={onClick}
>
  {label}
</button>

// code/frameworks/angular/template/stories_angular-cli-prerelease/signal/button.component.ts
import { Component, Input, Output, EventEmitter, input } from '@angular/core';

@Component({
  // Needs to be a different name to the CLI template button
  selector: 'storybook-signal-button',
  template: ` <button
    type="button"
    (click)="onClick.emit($event)"
    [ngClass]="classes"
    [ngStyle]="{ 'background-color': backgroundColor }"
  >
    {{ label() }}
  </button>`,
  styleUrls: ['./button.css'],
})
export default class SignalButtonComponent {
  /**
   * Is this the principal call to action on the page?
   */
  primary = input(false);

  /**
   * What background color to use
   */
  @Input()
  backgroundColor?: string;

  /**
   * How large should the button be?
   */
  size = input('medium', {
    transform: (val: 'small' | 'medium') => val,
  });

  /**
   * Button contents
   */
  label = input.required({ transform: (val: string) => val.trim() });

  /**
   * Optional click handler
   */
  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): string[] {
    const mode = this.primary() ? 'storybook-button--primary' : 'storybook-button--secondary';

    return ['storybook-button', `storybook-button--${this.size()}`, mode];
  }
}
