// app/lit-element/src/client/preview/render.ts
import { document } from 'global';
import { stripIndents } from 'common-tags';
import { TemplateResult, LitElement } from 'lit-element';
import { RenderMainArgs } from './types';

const rootElement = document.getElementById('root');

export default function renderMain({
  storyFn,
  selectedKind,
  selectedStory,
  showMain,
  showError,
  forceRender,
}: RenderMainArgs) {
  const element = storyFn();

  if (!element) {
    showError({
      title: `Expecting a LitElement component from the story: "${selectedStory}" of "${selectedKind}".`,
      description: stripIndents`
        Did you forget to return the Polymer component from the story?
        Use "() => '&lt;your-component-name&gt;&lt;/your-component-name\&gt;'" when defining the story.
      `,
    });
    return;
  }

  showMain();
  if (typeof element === 'string') {
    rootElement.innerHTML = element;
  } else if (element instanceof TemplateResult) {
    // `render` stores the TemplateInstance in the Node and tries to update based on that.
    // Since we reuse `rootElement` for all stories, remove the stored instance first.
    // But forceRender means that it's the same story, so we want too keep the state in that case.
    if (!forceRender || !rootElement.querySelector('[id="root-inner"]')) {
      rootElement.innerHTML = '<div id="root-inner"></div>';
    }
    const renderTo = rootElement.querySelector('[id="root-inner"]');

    LitElement.render(element, renderTo, { scopeName: '' });
  } else {
    rootElement.innerHTML = '';
    rootElement.appendChild(element);
  }
}

// app/react/src/client/preview/render.tsx
import { document } from 'global';
import React from 'react';
import ReactDOM from 'react-dom';
import { render } from '@storybook/renderer-react';

import { RenderMainArgs } from './types';

const rootEl = document ? document.getElementById('root') : null;

export default function renderMain({
  storyFn: StoryFn,
  selectedKind,
  selectedStory,
  showMain,
  forceRender,
}: RenderMainArgs) {
  const element = <StoryFn />;

  // We need to unmount the existing set of components in the DOM node.
  // Otherwise, React may not recreate instances for every story run.
  // This could leads to issues like below:
  // https://github.com/storybookjs/react-storybook/issues/81
  // But forceRender means that it's the same story, so we want too keep the state in that case.
  if (!forceRender) {
    ReactDOM.unmountComponentAtNode(rootEl);
  }

  render(element, rootEl, { name: selectedStory, kind: selectedKind });
  showMain();
}
