// app/web-components/src/client/preview/render.ts
import { document, Node } from 'global';
import dedent from 'ts-dedent';
import { render, TemplateResult } from 'lit-html';
import { simulatePageLoad, simulateDOMContentLoaded } from '@storybook/client-api';
import { RenderContext } from './types';

const rootElement = document.getElementById('root');

export default function renderMain({
  storyFn,
  kind,
  name,
  showMain,
  showError,
  forceRender,
  targetDOMNode = rootElement,
}: RenderContext) {
  const element = storyFn();

  showMain();
  if (element instanceof TemplateResult) {
    // `render` stores the TemplateInstance in the Node and tries to update based on that.
    // Since we reuse `rootElement` for all stories, remove the stored instance first.
    // But forceRender means that it's the same story, so we want too keep the state in that case.
    if (!forceRender || !rootElement.querySelector('[id="root-inner"]')) {
      targetDOMNode.innerHTML = '<div id="root-inner"></div>';
    }
    const renderTo = targetDOMNode.querySelector('[id="root-inner"]');

    render(element, renderTo);
    simulatePageLoad(targetDOMNode);
  } else if (typeof element === 'string') {
    targetDOMNode.innerHTML = element;
    simulatePageLoad(targetDOMNode);
  } else if (element instanceof Node) {
    // Don't re-mount the element if it didn't change and neither did the story
    if (targetDOMNode.firstChild === element && forceRender === true) {
      return;
    }

    targetDOMNode.innerHTML = '';
    targetDOMNode.appendChild(element);
    simulateDOMContentLoaded();
  } else {
    showError({
      title: `Expecting an HTML snippet or DOM node from the story: "${name}" of "${kind}".`,
      description: dedent`
        Did you forget to return the HTML snippet from the story?
        Use "() => <your snippet or node>" or when defining the story.
      `,
    });
  }
}

// app/react/src/client/preview/render.tsx
import { document } from 'global';
import React from 'react';
import ReactDOM from 'react-dom';
import { render } from '@storybook/renderer-react';

import { RenderMainArgs } from './types';

const rootEl = document ? document.getElementById('root') : null;

export default function renderMain({
  storyFn: StoryFn,
  selectedKind,
  selectedStory,
  showMain,
  forceRender,
}: RenderMainArgs) {
  const element = <StoryFn />;

  // We need to unmount the existing set of components in the DOM node.
  // Otherwise, React may not recreate instances for every story run.
  // This could leads to issues like below:
  // https://github.com/storybookjs/react-storybook/issues/81
  // But forceRender means that it's the same story, so we want too keep the state in that case.
  if (!forceRender) {
    ReactDOM.unmountComponentAtNode(rootEl);
  }

  render(element, rootEl, { name: selectedStory, kind: selectedKind });
  showMain();
}
