// code/renderers/react/src/types.ts
import type { ComponentType, ReactElement } from 'react';
import type { AnyFramework } from '@storybook/csf';

export type { RenderContext } from '@storybook/store';
export type { StoryContext } from '@storybook/csf';

export interface ReactFramework extends AnyFramework {
  component: ComponentType<this['T']>;
  storyResult: StoryFnReactReturnType;
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}

export type StoryFnReactReturnType = ReactElement<unknown>;

export interface IStorybookStory {
  name: string;
  render: (context: any) => any;
}

export interface IStorybookSection {
  kind: string;
  stories: IStorybookStory[];
}

// renderers/web-components/src/types.ts
import type {
  ComponentAnnotations,
  StoryAnnotations,
  AnnotatedStoryFn,
  Args,
  ArgTypes,
  Parameters,
  StoryContext as StoryContextBase,
} from '@storybook/csf';
import type { TemplateResult, SVGTemplateResult } from 'lit-html';

export type StoryFnHtmlReturnType = string | Node | TemplateResult | SVGTemplateResult;

export type StoryContext = StoryContextBase<WebComponentsFramework>;

export type WebComponentsFramework = {
  component: string;
  storyResult: StoryFnHtmlReturnType;
};

export interface IStorybookStory {
  name: string;
  render: (context: any) => any;
}

export interface IStorybookSection {
  kind: string;
  stories: IStorybookStory[];
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}
