// code/renderers/vue3/template/components/Pre.vue
<template>
  <pre data-testid="pre" :style="style">{{ text }}</pre>
</template>

<script>
import { reactive, computed } from 'vue';

export default {
  name: 'my-pre',

  props: {
    style: {
      type: Object,
    },
    object: {
      type: Object,
    },
    text: {
      type: String,
      default: '',
    },
  },

  setup(props, { emit }) {
    props = reactive(props);
    return {
      text: computed(() => (props.object ? JSON.stringify(props.object, null, 2) : props.text)),
    };
  },
};
</script>

// code/renderers/preact/template/components/Pre.jsx
/**
 * Pre component
 * @param {object} props
 * @param {object} [props.style]
 * @param {object} [props.object]
 * @param {string} [props.text]
 */
export const Pre = ({ style = {}, object = null, text = '' }) => (
  <pre style={style} data-testid="pre">
    {object ? JSON.stringify(object, null, 2) : text}
  </pre>
);
